import React from "react";
import "./globals.css"; // Importation des styles globaux
import NavBar from "../components/NavBar"; // Si NavBar existe

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <NavBar /> {/* Barre de navigation */}
        <main className="container mx-auto mt-8">{children}</main> {/* Contenu principal */}
      </body>
    </html>
  );
}
